CREATE DATABASE IF NOT EXISTS t;

CREATE TABLE IF NOT EXISTS t.src (id UInt64, v UInt64) ENGINE=MergeTree ORDER BY id;
INSERT INTO t.src SELECT number, number*2 FROM numbers(1000);

-- REPLACE mode, implicit inner table (no TO), EVERY
CREATE MATERIALIZED VIEW IF NOT EXISTS t.mv_replace
REFRESH EVERY 1 YEAR
ENGINE = MergeTree ORDER BY id
AS SELECT id, v FROM t.src;

-- REPLACE mode with explicit TO target
CREATE TABLE IF NOT EXISTS t.tgt (id UInt64, v UInt64) ENGINE=MergeTree ORDER BY id;
CREATE MATERIALIZED VIEW IF NOT EXISTS t.mv_to
REFRESH EVERY 1 YEAR
TO t.tgt
AS SELECT id, v FROM t.src;

-- APPEND mode
CREATE MATERIALIZED VIEW IF NOT EXISTS t.mv_append
REFRESH EVERY 1 YEAR APPEND
ENGINE = MergeTree ORDER BY id
AS SELECT id, v FROM t.src;

-- EVERY with OFFSET + RANDOMIZE FOR
CREATE MATERIALIZED VIEW IF NOT EXISTS t.mv_rand
REFRESH EVERY 1 DAY OFFSET 1 HOUR RANDOMIZE FOR 10 MINUTE
ENGINE = MergeTree ORDER BY id
AS SELECT id, v FROM t.src;

-- DEPENDS ON with EVERY (expected to succeed)
CREATE MATERIALIZED VIEW IF NOT EXISTS t.mv_dep
REFRESH EVERY 1 YEAR DEPENDS ON t.mv_replace
ENGINE = MergeTree ORDER BY id
AS SELECT id, v FROM t.mv_replace;

-- REFRESH AFTER mode (no depends)
CREATE MATERIALIZED VIEW IF NOT EXISTS t.mv_after
REFRESH AFTER 1 YEAR
ENGINE = MergeTree ORDER BY id
AS SELECT id, v FROM t.src;
